# Generated by Django 3.0.7 on 2020-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productData', models.CharField(max_length=50)),
                ('dfv', models.CharField(max_length=50)),
                ('variation', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('checks', models.CharField(default=0, max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('schedule', models.CharField(default=0, max_length=50)),
                ('stock', models.CharField(max_length=50)),
            ],
        ),
    ]
